[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    "v4-core/=lib/v4-core/",
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "forge-std/=lib/forge-std/src/"
]

# Solidity compiler settings
solc_version = "0.8.26"
evm_version = "cancun"
optimizer = true
optimizer_runs = 1000000
via_ir = true

# Test settings
verbosity = 2
gas_reports = ["*"]
gas_reports_ignore = ["test/**/*"]

# Fork testing configuration
[rpc_endpoints]
mainnet = "${ETHEREUM_RPC_URL}"
sepolia = "${SEPOLIA_RPC_URL}"

[etherscan]
mainnet = { key = "${ETHERSCAN_API_KEY}" }
sepolia = { key = "${ETHERSCAN_API_KEY}" }

# Fuzz testing
[fuzz]
runs = 1000
max_test_rejects = 65536
seed = '0x3e8'
dictionary_weight = 40
include_storage = true
include_push_bytes = true

# Invariant testing
[invariant]
runs = 256
depth = 15
fail_on_revert = false
call_override = false
dictionary_weight = 80
include_storage = true
include_push_bytes = true

# Gas snapshots
[profile.snapshot]
dir = "snapshots"
file = ".gas-snapshot"

# Documentation
[doc]
out = "docs"
title = "Lending Liquidity Guardian Hook"
book = "book.toml"
repository = "https://github.com/your-org/lending-liquidity-guardian"

# Formatting
[fmt]
line_length = 100
tab_width = 4
bracket_spacing = true
int_types = "long"
multiline_func_header = "all"
quote_style = "double"
number_underscore = "thousands"
single_line_statement_blocks = "preserve"